#:schema node_modules/wrangler/config-schema.json
name = "exotext"
main = "src/index.ts"
assets = { directory = "./public/" }

compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-10-22"

routes = [
  { pattern = "exotext.com", custom_domain = true },
  { pattern = "*exotext.com/*", zone_name = "exotext.com" }
]

[placement]
mode = "smart"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "exotext"
database_id = "4b0d1f02-b9bc-4f89-a18b-a3f70db93807"

[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "bda520fade10435b8cecf65b3af9e799"
preview_id = "90c4c44b69f14a21b4cc0fefef1f3bb6"

[[r2_buckets]]
binding = 'IMG_BUCKET'
bucket_name = 'exotext-img'
